#!/bin/bash

echo "Run training script..."

datetime="$1" # $1 refers to the first command-line argument

# check if datetime is empty. If so, set it to current datetime.
if [ -z "$datetime" ]; then
    datetime=$(date +"%Y-%m-%d_%H-%M-%S")
fi

git reset --hard
git checkout ac9cf5ef

seeds=(1)
for seed in "${seeds[@]}"; do
    ./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py env.amp_motion_folder='datasets/fromVision_motions_DepthCamStairs/*' agent.amp_motion_folder='agent.amp_motion_folder=datasets/fromVision_motions_DepthCamStairs/*' --task Isaac-Velocity-AMPStairs-Unitree-Go2-v0 --headless --seed $seed --log_dir "${datetime}_paperAMP6" --logger wandb --log_project_name paper_amp --max_iterations 25000
done

git reset --hard
git checkout mocap_exp

# ./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py env.amp_motion_folder='datasets/mocap_AMP_for_hardware/*' agent.amp_motion_folder='datasets/mocap_AMP_for_hardware/*' --task Isaac-Velocity-AMPStairs-Unitree-Go2-v0 --headless --seed 1 --log_dir "${datetime}_paperAMP6" --logger wandb --log_project_name paper_amp & ./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py env.amp_motion_folder='datasets/mocap_AMP_for_hardware/*' agent.amp_motion_folder='datasets/mocap_AMP_for_hardware/*' --task Isaac-Velocity-AMPStairs-Unitree-Go2-v0 --headless --seed 2 --log_dir "${datetime}_paper_mocap" --logger wandb --log_project_name paper_mocap
./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py env.amp_motion_folder='datasets/mocap_AMP_for_hardware/*' agent.amp_motion_folder='datasets/mocap_AMP_for_hardware/*' --task Isaac-Velocity-AMPStairs-Unitree-Go2-v0 --headless --seed 3 --log_dir "${datetime}_paper_mocap" --logger wandb --log_project_name paper_mocap --max_iterations 25000
